server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/infect_statistic?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    suffix: .html
    prefix: classpath:/templates/

mybatis:
  mapper-locations: classpath:/generator/*.xml
  type-aliases-package: edu.fzu.infect.generator
  configuration:
    map-underscore-to-camel-case: true

logging:
  config: classpath:log4j2-dev.xml
